languageCode = "en-us"
title = "DEH Summer Institute 2021"
baseURL = "jeremyfprice.github.io/dehsi2021/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "The Digital Education Hub Summer Institute Online Workbook."
  codePenUser = "Heydon"
